CREATE DATABASE IF NOT EXISTS salao
CHARACTER SET utf8mb4
COLLATE utf8mb4_unicode_ci;

USE salao;

CREATE TABLE IF NOT EXISTS servico (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    duracao INT NOT NULL,
    preco DECIMAL(10,2) NOT NULL
);